# Generated by Django 3.0 on 2020-02-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=50)),
                ('customerAddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PackageName', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=600)),
                ('PackageCost', models.CharField(max_length=50)),
                ('PackageDays', models.CharField(default=2, max_length=20)),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Days', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Package')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
