# Generated by Django 3.0 on 2020-02-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='PackageImage',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
