# Generated by Django 3.0 on 2020-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_package_packageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='PackageImage',
            field=models.ImageField(default='img.jpg', upload_to='images/'),
        ),
    ]
