# Generated by Django 3.0 on 2020-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200206_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='PackageImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
